# Generated by Django 2.2.4 on 2019-10-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='rpassword',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='phone',
            new_name='mobno',
        ),
    ]
